project:
  type: website
  output-dir: docs

website:
  title: Class-Presentation
  description:"Gas Exchange at the Alveoli"
  site-url: https://kellypurdy15.github.io/Class-Presentation
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kellypurdy15/Class-Presentation

date-format: X
date: last-modified

format:
  html:
    theme: simple



